name: Publish Scrubby.Web Container
on:
  release:
    types: [created]
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Scrubby.Web server image
        run: dotnet publish Scrubby.Web -p:PublishProfile=DefaultContainer -c Release
